export enum Language {
    Java = "Java",
    SpringBoot = "SpringBoot",
    Kotlin = "Kotlin",
    Jetpack = "Jetpack",
    Swift = "Swift",
    SwiftUI = "SwiftUI",
    Flutter = "Flutter",
    JavaScript = "JavaScript",
    TypeScript = "TypeScript",
    React = "React",
    NodeJS = "NodeJS",
    TailwindCSS = "TailwindCSS",
    HTML = "HTML",
    CSS = "CSS",
    DART = "DART",
}